// Do not edit! Generated by etc/update-libcxx.sh
// SPDX-License-Identifier: Apache-2.0

static const char* libcxxabi_sources[] = {
  "abort_message.cpp",
  "cxa_aux_runtime.cpp",
  "cxa_default_handlers.cpp",
  "cxa_demangle.cpp",
  "cxa_exception.cpp",
  "cxa_exception_storage.cpp",
  "cxa_guard.cpp",
  "cxa_handlers.cpp",
  "cxa_noexception.cpp",
  "cxa_personality.cpp",
  "cxa_thread_atexit.cpp",
  "cxa_vector.cpp",
  "cxa_virtual.cpp",
  "fallback_malloc.cpp",
  "private_typeinfo.cpp",
  "stdlib_exception.cpp",
  "stdlib_new_delete.cpp",
  "stdlib_stdexcept.cpp",
  "stdlib_typeinfo.cpp",
};
