// Do not edit! Generated by etc/update-libcxx.sh
// SPDX-License-Identifier: Apache-2.0

static const char* libunwind_sources[] = {
  "libunwind.cpp",
  "Unwind-EHABI.cpp",
  "Unwind-seh.cpp",
  "Unwind-sjlj.c",
  "UnwindLevel1-gcc-ext.c",
  "UnwindLevel1.c",
  "UnwindRegistersRestore.S",
  "UnwindRegistersSave.S",
  "Unwind_AIXExtras.cpp",
  "Unwind_AppleExtras.cpp",
};
