_( TEOF, "eof" )

_( TSEMI,   ";" )
_( TINDENT, "indentation" )
_( TDEDENT, "indentation drop" )

_( TLPAREN, "(" ) _( TRPAREN, ")" )
_( TLBRACE, "{" ) _( TRBRACE, "}" )
_( TLBRACK, "[" ) _( TRBRACK, "]" )

_( TDOT,        "." )
_( TDOTDOT,     ".." )
_( TDOTDOTDOT,  "..." )
_( TCOLON,      ":" )
_( TCOLONCOLON, "::" )
_( TSEMICOLON,  ";" )
_( TCOMMA,      "," )
_( THASH,       "#" )
_( TQUESTION,   "?" )
_( TARROWRIGHT, "->" )

_( TPLUS,       "+" )
_( TPLUSPLUS,   "++" )
_( TMINUS,      "-" )
_( TMINUSMINUS, "--" )
_( TSTAR,       "*" )
_( TSLASH,      "/" )
_( TPERCENT,    "%" )
_( TTILDE,      "~" )
_( TNOT,        "!" )
_( TAND,        "&" )
_( TANDAND,     "&&" )
_( TOR,         "|" )
_( TOROR,       "||" )
_( TXOR,        "^" )
_( TSHL,        "<<" )
_( TSHR,        ">>" )

_( TEQ,   "==" )
_( TNEQ,  "!=" )
_( TLT,   "<" )
_( TGT,   ">" )
_( TLTEQ, "<=" )
_( TGTEQ, ">=" )

_( TASSIGN,    "=" )
_( TMULASSIGN, "*=" )
_( TDIVASSIGN, "/=" )
_( TMODASSIGN, "%=" )
_( TADDASSIGN, "+=" )
_( TSUBASSIGN, "-=" )
_( TSHLASSIGN, "<<=" )
_( TSHRASSIGN, ">>=" )
_( TANDASSIGN, "&=" )
_( TXORASSIGN, "^=" )
_( TORASSIGN,  "|=" )

_( TID, "identifier" )
_( TINTLIT, "integer literal" )
_( TFLOATLIT, "number literal" )
_( TBYTELIT, "byte literal" )
_( TSTRLIT, "string literal" )
_( TCOMMENT, "comment" )

// keywords (must be sorted)

// KEYWORD( "as",       TAS )
// KEYWORD( "auto",     TAUTO )
// KEYWORD( "break",    TBREAK )
// KEYWORD( "const",    TCONST )
// KEYWORD( "continue", TCONTINUE )
// KEYWORD( "defer",    TDEFER )
// KEYWORD( "else",     TELSE )
// KEYWORD( "enum",     TENUM )
// KEYWORD( "for",      TFOR )
KEYWORD( "fun",      TFUN )
// KEYWORD( "if",       TIF )
// KEYWORD( "import",   TIMPORT )
// KEYWORD( "in",       TIN )
KEYWORD( "int",      TINT )
// KEYWORD( "mut",      TMUT )
// KEYWORD( "nil",      TNIL )
// KEYWORD( "return",   TRETURN )
// KEYWORD( "struct",   TSTRUCT )
// KEYWORD( "switch",   TSWITCH )
// KEYWORD( "type",     TTYPE )
// KEYWORD( "unsafe",   TUNSAFE )
// KEYWORD( "var",      TVAR )


